# Generated by Django 4.2.7 on 2024-05-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('age_range', models.CharField(choices=[('18-24', '18-24'), ('25-30', '25-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('>50', '>50')], max_length=10, null=True)),
                ('categorie_socioprofessionnelle', models.CharField(choices=[('etudiant', 'Étudiant'), ('employe', 'Employé'), ('cadre', 'Cadre'), ('travailleur_independant', 'Travailleur indépendant'), ('sans_emploi', 'Sans emploi'), ('autre', 'Autre')], max_length=50, null=True)),
                ('autre_categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(choices=[('Agadir', 'Agadir'), ('Al Hoceima', 'Al Hoceima'), ('Asilah', 'Asilah'), ('Azemmour', 'Azemmour'), ('Azrou', 'Azrou'), ('Beni Mellal', 'Beni Mellal'), ('Berkane', 'Berkane'), ('Berrechid', 'Berrechid'), ('Boujdour', 'Boujdour'), ('Casablanca', 'Casablanca'), ('Chefchaouen', 'Chefchaouen'), ('Dakhla', 'Dakhla'), ('El Jadida', 'El Jadida'), ('Errachidia', 'Errachidia'), ('Essaouira', 'Essaouira'), ('Fes', 'Fes'), ('Fnideq', 'Fnideq'), ('Guelmim', 'Guelmim'), ('Ifrane', 'Ifrane'), ('Khenifra', 'Khenifra'), ('Khmissat', 'Khmissat'), ('Khouribga', 'Khouribga'), ('Laayoune', 'Laayoune'), ('Larache', 'Larache'), ('Marrakech', 'Marrakech'), ('Martil', 'Martil'), ('Meknes', 'Meknes'), ('Mohammedia', 'Mohammedia'), ('Nador', 'Nador'), ('Ouarzazate', 'Ouarzazate'), ('Oued Zem', 'Oued Zem'), ('Oujda', 'Oujda'), ('Rabat', 'Rabat'), ('Safi', 'Safi'), ('Salé', 'Salé'), ('Sefrou', 'Sefrou'), ('Settat', 'Settat'), ('Sidi Kacem', 'Sidi Kacem'), ('Sidi Slimane', 'Sidi Slimane'), ('Sidi Yahya El Gharb', 'Sidi Yahya El Gharb'), ('Skhirat', 'Skhirat'), ('Tanger', 'Tanger'), ('Tan-Tan', 'Tan-Tan'), ('Taza', 'Taza'), ('Temara', 'Temara'), ('Tetouan', 'Tetouan'), ('Tiflet', 'Tiflet'), ('Tiznit', 'Tiznit'), ('Youssoufia', 'Youssoufia')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.candidat')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.choice')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_name', models.CharField(max_length=100)),
                ('liked', models.BooleanField()),
                ('comment', models.TextField()),
                ('type_personality', models.CharField(max_length=50, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Percandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyn', models.BooleanField(default=False)),
                ('commantaire', models.CharField(max_length=400, null=True)),
                ('psayn', models.BooleanField(default=False)),
                ('commantaire_sa', models.CharField(max_length=400, null=True)),
                ('psbyn', models.BooleanField(default=False)),
                ('commantaire_sb', models.CharField(max_length=400, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.candidat')),
                ('personalite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percandidat_personalite_pyn', to='TestPersonality.personality')),
                ('personalite_sa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percandidat_personalite_personalite_sa', to='TestPersonality.personality')),
                ('personalite_sb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percandidat_personalite_personalite_sb', to='TestPersonality.personality')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('dislikes', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('type_personality', models.CharField(max_length=50, null=True)),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.personality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.candidat')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='personalities',
            field=models.ManyToManyField(to='TestPersonality.personality'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestPersonality.question'),
        ),
    ]
