# Generated by Django 4.2.13 on 2024-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPersonality', '0002_alter_candidat_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('support', models.BooleanField(default=False)),
            ],
        ),
    ]
